<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Build.Tasks.Git" Version="10.0.111">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.10" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="8.0.4" />
    <PackageReference Include="WindowsAzure.Storage" Version="9.3.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Naideth-v1-Central\1.Dominio\Naideth.Central.Dominio\Naideth.Central.Dominio.csproj" />
    <ProjectReference Include="..\..\1.Dominio\Naideth.Traslados.Dominio\Naideth.Traslados.Dominio.csproj" />
    <ProjectReference Include="..\..\2.Aplicacion\Naideth.Traslados.Aplicacion\Naideth.Traslados.Aplicacion.csproj" />
  </ItemGroup>

</Project>
